matrix:
- name: markdown
  aspell:
    lang: en
    ignore-case: true
    d: en_US
    mode: markdown
  dictionary:
    wordlists:
    - .github/config/.wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  sources:
  - '**/*.md'
  default_encoding: utf-8
